#!/bin/bash

BINDIR=`pwd`
BASEDIR=`dirname $0`
DIFF=diff
TESTCELEDS=$BINDIR/testCeLEDS
TEMPFILE=test_celeds_output
LANGUAGE=C

if [[ ! -f "$TESTCELEDS" ]]; then
        echo testCeLEDS not found. Not testing it.
        exit 77
fi

if [[ -n $RUNNER ]]; then
    TESTCELEDS="$RUNNER $BINDIR/.libs/testCeLEDS.exe"
fi

function runtest()
{
  name=$1;
  rm -f $TEMPFILE;
  $TESTCELEDS $BASEDIR/test_xml/$name.xml $BINDIR/CeLEDS/languages/$LANGUAGE.xml > $TEMPFILE
  FAIL=0
  $DIFF -bu $TEMPFILE $BASEDIR/test_celeds_expected/$name.c
  if [[ $? -ne 0 ]]; then
    if [[ -f $BASEDIR/test_celeds_expected/$name-alt1.c ]]; then
        $DIFF -bu $TEMPFILE $BASEDIR/test_celeds_expected/$name-alt1.c
        if [[ $? -ne 0 ]]; then
            if [[ -f $BASEDIR/test_celeds_expected/$name-alt2.c ]]; then
                $DIFF -bu $TEMPFILE $BASEDIR/test_celeds_expected/$name-alt2.c
                if [[ $? -ne 0 ]]; then
                    if [[ -f $BASEDIR/test_celeds_expected/$name-alt3.c ]]; then
                        $DIFF -bu $TEMPFILE $BASEDIR/test_celeds_expected/$name-alt3.c
                        FAIL=$?
                    else
                        FAIL=1
                    fi
                fi
            else
                FAIL=1
            fi
        fi
    else
        FAIL=1
    fi
  fi
  if [[ $FAIL -ne 0 ]]; then
    echo FAIL: $name generated wrong output.
    rm -f $TEMPFILE
    exit 1
  fi
  echo PASS: $name generated correct output.
  rm -f $TEMPFILE
}

runtest cellml_simple_test
runtest modified_parabola
runtest underconstrained_1
runtest overconstrained_1
runtest newton_raphson_parabola
runtest import_eqn
runtest number-minus
runtest units
runtest units-import
runtest units-import-import
runtest units-in-imported-component
runtest SimpleDAE_NonLinear

exit 0
