#!/bin/bash

BINDIR=`pwd`
BASEDIR=`dirname $0`/..
cd $BASEDIR
DIFF="./tests/ndiff -t 1%"
RUNCELLML=$BINDIR/RunCellML
TEMPFILE=test_output.$$

if [[ ! -f "$RUNCELLML" ]]; then
        echo RunCellML not found. Not testing it.
        exit 77
fi

if [[ -n $RUNNER ]]; then
    RUNCELLML="$RUNNER $BINDIR/.libs/RunCellML.exe"
fi
RUNCELLML="$TESTS_ENVIRONMENT $RUNCELLML"

grep -q "s,#define ENABLE_RDF,g" $BINDIR/cda_config.h
RDF_ENABLED=$?

if [[ $(uname -o) == 'Cygwin' ]]; then
  export LIBRARY_PATH="$BINDIR;$LIBRARY_PATH"
else
  export LIBRARY_PATH="$BINDIR:$LIBRARY_PATH"
fi

function runtest()
{
  name=$1;
  args=$2
  rm -f $TEMPFILE;
  $RUNCELLML ./tests/test_xml/$name.xml tabulation 0.1,true step_size_control 1E-6,1E-6 $args | tr -d "\r" >$TEMPFILE
  FAIL=0
  $DIFF -bu $TEMPFILE ./tests/test_expected/$name.csv
  if [[ $? -ne 0 ]]; then
    if [[ -f ./tests/test_expected/$name-alt1.csv ]]; then
        $DIFF -bu $TEMPFILE ./tests/test_expected/$name-alt1.csv
        if [[ $? -ne 0 ]]; then
            if [[ -f ./tests/test_expected/$name-alt2.csv ]]; then
                $DIFF -bu $TEMPFILE ./tests/test_expected/$name-alt2.csv
                if [[ $? -ne 0 ]]; then
                    if [[ -f ./tests/test_expected/$name-alt3.csv ]]; then
                        $DIFF -bu $TEMPFILE ./tests/test_expected/$name-alt3.csv
                        FAIL=$?
                    else
                        FAIL=1
                    fi
                fi
            else
                FAIL=1
            fi
        fi
    else
        FAIL=1
    fi
  fi
  if [[ $FAIL -ne 0 ]]; then
    echo FAIL: $name generated wrong output.
    rm -f $TEMPFILE
    exit 1
  fi
  echo PASS: $name generated correct output.
  rm -f $TEMPFILE
}

function runWithArgs()
{
  args="$1"
  runtest cellml_simple_test "$args"
  runtest modified_parabola "$args"
  runtest underconstrained_1 "$args"
  runtest overconstrained_1 "$args"
  runtest newton_raphson_parabola "$args"
  runtest import_eqn "$args"
  runtest number-minus "$args"
  runtest units "$args"
  runtest units-import "$args"
  runtest units-import-import "$args"
  runtest units-in-imported-component "$args"
  runtest SimpleDAE_NonLinear "$args"
  #runtest_rdf newton_raphson_parabola_overrideiv $args
  #runtest_usenames modified_parabola $args
  runtest StateModel "$args"
  runtest reset_rule "$args"
  runtest definite_integral "$args"
  runtest TestParameterIVAmbiguity "$args"
  runtest IVComputation "$args"
  runtest defint-constant "$args"
}

runWithArgs "step_type IDA debug true"
runWithArgs "step_type AM_1_12 debug true"
runWithArgs "step_type AM_1_12"

exit 0
