#!/bin/bash

BINDIR=`pwd`
BASEDIR=`dirname $0`
DIFF=diff
CELLML2C=$BINDIR/CellML2C
TEMPFILE=test_output

if [[ ! -f "$CELLML2C" ]]; then
        echo CellML2C not found. Not testing it.
        exit 77
fi

if [[ -n $RUNNER ]]; then
    CELLML2C="$RUNNER $BINDIR/.libs/CellML2C.exe"
fi

function runtest()
{
  name=$1;
  rm -f $TEMPFILE;
  $CELLML2C $BASEDIR/test_xml/$name.xml >$TEMPFILE
  FAIL=0
  $DIFF -b $TEMPFILE $BASEDIR/test_expected/$name.c
  if [[ $? -ne 0 ]]; then
    if [[ -f $BASEDIR/test_expected/$name-alt1.c ]]; then
        $DIFF -b $TEMPFILE $BASEDIR/test_expected/$name-alt1.c
        FAIL=$?
    else
        FAIL=1
    fi
  fi
  if [[ $FAIL -ne 0 ]]; then
    echo FAIL: $name generated wrong output.
    rm -f $TEMPFILE
    exit 1
  fi
  echo PASS: $name generated correct output.
  rm -f $TEMPFILE
}

runtest cellml_simple_test
runtest modified_parabola
runtest underconstrained_1
runtest overconstrained_1
runtest newton_raphson_parabola
runtest import_eqn
runtest number-minus
runtest units
runtest units-import
runtest units-import-import
runtest units-in-imported-component

exit 0
