#!/bin/bash

BASEDIR=`dirname $0`/..

cd $BASEDIR

DIFF=diff
TESTCELEDS=./testCeLEDS
TEMPFILE=test_celeds_output
LANGUAGE=C

if [[ ! -f "$TESTCELEDS" ]]; then
        echo testCeLEDS not found. Not testing it.
        exit 77
fi

if [[ -n $RUNNER ]]; then
    TESTCELEDS="$RUNNER $BINDIR/.libs/testCeLEDS.exe"
fi

function runtest()
{
  name=$1;
  rm -f $TEMPFILE;
  $TESTCELEDS ./tests/test_xml/$name.xml ./CeLEDS/languages/$LANGUAGE.xml | tr -d "\r" | sed -e "s/0.000000/0.00000/" > $TEMPFILE
  FAIL=0
  $DIFF -bu $TEMPFILE tests/test_celeds_expected/$name.c
  if [[ $? -ne 0 ]]; then
    if [[ -f tests/test_celeds_expected/$name-alt1.c ]]; then
        $DIFF -bu $TEMPFILE tests/test_celeds_expected/$name-alt1.c
        if [[ $? -ne 0 ]]; then
            if [[ -f tests/test_celeds_expected/$name-alt2.c ]]; then
                $DIFF -bu $TEMPFILE tests/test_celeds_expected/$name-alt2.c
                if [[ $? -ne 0 ]]; then
                    if [[ -f tests/test_celeds_expected/$name-alt3.c ]]; then
                        $DIFF -bu $TEMPFILE tests/test_celeds_expected/$name-alt3.c
                        FAIL=$?
                    else
                        FAIL=1
                    fi
                fi
            else
                FAIL=1
            fi
        fi
    else
        FAIL=1
    fi
  fi
  if [[ $FAIL -ne 0 ]]; then
    echo FAIL: $name generated wrong output.
    rm -f $TEMPFILE
    exit 1
  fi
  echo PASS: $name generated correct output.
  rm -f $TEMPFILE
}

runtest cellml_simple_test
runtest modified_parabola
runtest underconstrained_1
runtest overconstrained_1
runtest newton_raphson_parabola
runtest import_eqn
runtest number-minus
runtest units
runtest units-import
runtest units-import-import
runtest units-in-imported-component
runtest SimpleDAE_NonLinear
runtest StateModel

exit 0
