#!/bin/bash

BINDIR=`pwd`
BASEDIR=`dirname $0`
DIFF=diff
CELLML2C=$BINDIR/CellML2C
TEMPFILE=test_output

if [[ ! -f "$CELLML2C" ]]; then
        echo CellML2C not found. Not testing it.
        exit 77
fi

if [[ -n $RUNNER ]]; then
    CELLML2C="$RUNNER $BINDIR/.libs/CellML2C.exe"
fi

function runtest()
{
  name=$1;
  rm -f $TEMPFILE;
  $CELLML2C $BASEDIR/test_xml/$name.xml >$TEMPFILE
  FAIL=0
  $DIFF -bu $TEMPFILE $BASEDIR/test_expected/$name.c
  if [[ $? -ne 0 ]]; then
    if [[ -f $BASEDIR/test_expected/$name-alt1.c ]]; then
        $DIFF -bu $TEMPFILE $BASEDIR/test_expected/$name-alt1.c
        if [[ $? -ne 0 ]]; then
            if [[ -f $BASEDIR/test_expected/$name-alt2.c ]]; then
                $DIFF -bu $TEMPFILE $BASEDIR/test_expected/$name-alt2.c
                if [[ $? -ne 0 ]]; then
                    if [[ -f $BASEDIR/test_expected/$name-alt3.c ]]; then
                        $DIFF -bu $TEMPFILE $BASEDIR/test_expected/$name-alt3.c
                        FAIL=$?
                    else
                        FAIL=1
                    fi
                fi
            else
                FAIL=1
            fi
        fi
    else
        FAIL=1
    fi
  fi
  if [[ $FAIL -ne 0 ]]; then
    echo FAIL: $name generated wrong output.
    rm -f $TEMPFILE
    exit 1
  fi
  echo PASS: $name generated correct output.
  rm -f $TEMPFILE
}

function runtest_usenames()
{
  name=$1;
  rm -f $TEMPFILE;
  $CELLML2C $BASEDIR/test_xml/$name.xml usenames >$TEMPFILE
  FAIL=0
  $DIFF -bu $TEMPFILE $BASEDIR/test_expected/$name-usenames.c
  FAIL=$?
  if [[ $FAIL -ne 0 ]]; then
    echo FAIL: $name with names generated wrong output.
    rm -f $TEMPFILE
    exit 1
  fi
  echo PASS: $name with names generated correct output.
  rm -f $TEMPFILE
}

runtest cellml_simple_test
runtest modified_parabola
runtest underconstrained_1
runtest overconstrained_1
runtest newton_raphson_parabola
runtest import_eqn
runtest number-minus
runtest units
runtest units-import
runtest units-import-import
runtest units-in-imported-component
runtest SimpleDAE_NonLinear

runtest_usenames modified_parabola

exit 0
