DECLARE_EXTENSION(malaes)
DECLARE_IDL(MaLaES)
DECLARE_IDL_DEPENDENCY(CeVAS)
DECLARE_IDL_DEPENDENCY(AnnoTools)
DECLARE_IDL_DEPENDENCY(CUSES)
DECLARE_EXTENSION_END(malaes)

INCLUDE_DIRECTORIES(MaLaES/sources)

ADD_LIBRARY(malaes
  MaLaES/sources/MaLaESImpl.cpp)
SET_TARGET_PROPERTIES(malaes PROPERTIES VERSION ${GLOBAL_VERSION} SOVERSION ${MALAES_SOVERSION})
INSTALL(TARGETS malaes
    EXPORT libcellml-config
    DESTINATION lib
    INCLUDES DESTINATION ${LIBCELLML_INCLUDE_DEST})
INSTALL(FILES MaLaES/sources/MaLaESBootstrap.hpp DESTINATION ${LIBCELLML_INCLUDE_DEST})
TARGET_LINK_LIBRARIES(malaes cellml ${CMAKE_DL_LIBS})

DECLARE_BOOTSTRAP("MaLaESBootstrap" "MaLaES" "MaLaESBootstrap" "cellml_services" "createMaLaESBootstrap" "CreateMaLaESBootstrap" "MaLaESBootstrap.hpp" "MaLaES/sources" "malaes")

DECLARE_CPPUNIT_FILE(MaLaES)
DECLARE_TEST_LIB(malaes)
