DECLARE_EXTENSION(malaes)
DECLARE_IDL(MaLaES)
DECLARE_IDL_DEPENDENCY(CeVAS)
DECLARE_IDL_DEPENDENCY(AnnoTools)
DECLARE_IDL_DEPENDENCY(CUSES)
DECLARE_EXTENSION_END(malaes)

INCLUDE_DIRECTORIES(MaLaES/sources)

ADD_LIBRARY(malaes
  MaLaES/sources/MaLaESImpl.cpp)
INSTALL(TARGETS malaes DESTINATION lib)
TARGET_LINK_LIBRARIES(malaes cellml ${CMAKE_DL_LIBS})

DECLARE_BOOTSTRAP("MaLaESBootstrap" "MaLaES" "MaLaESBootstrap" "cellml_services" "createMaLaESBootstrap" "CreateMaLaESBootstrap" "MaLaESBootstrap.hpp" "MaLaES/sources" "malaes")

DECLARE_CPPUNIT_FILE(MaLaES)
DECLARE_TEST_LIB(malaes)
