/* This file is automatically generated from MoFS.idl
 * DO NOT EDIT DIRECTLY OR CHANGES WILL BE LOST!
 */
#ifndef _GUARD_IFACE_MoFS
#define _GUARD_IFACE_MoFS
#include "cda_compiler_support.h"
#ifdef MODULE_CONTAINS_MoFS
#define PUBLIC_MoFS_PRE CDA_EXPORT_PRE
#define PUBLIC_MoFS_POST CDA_EXPORT_POST
#else
#define PUBLIC_MoFS_PRE CDA_IMPORT_PRE
#define PUBLIC_MoFS_POST CDA_IMPORT_POST
#endif
#include "Ifacexpcom.hxx"
#include "IfaceDOM_APISPEC.hxx"
#include "IfaceMathML_content_APISPEC.hxx"
#include "IfaceCellML_APISPEC.hxx"
namespace iface
{
  namespace mofs
  {
    PUBLIC_MoFS_PRE 
    class  PUBLIC_MoFS_POST ModelFlattener
     : public virtual iface::XPCOM::IObject
    {
    public:
      static const char* INTERFACE_NAME() { return "mofs::ModelFlattener"; }
      virtual ~ModelFlattener() {}
      virtual already_AddRefd<iface::cellml_api::Model>  flatten(iface::cellml_api::Model* aModel) throw(std::exception&) WARN_IF_RETURN_UNUSED = 0;
      virtual std::wstring lastError() throw(std::exception&)  WARN_IF_RETURN_UNUSED = 0;
    };
    PUBLIC_MoFS_PRE 
    class  PUBLIC_MoFS_POST ModelFlatteningService
     : public virtual iface::XPCOM::IObject
    {
    public:
      static const char* INTERFACE_NAME() { return "mofs::ModelFlatteningService"; }
      virtual ~ModelFlatteningService() {}
      virtual already_AddRefd<iface::mofs::ModelFlattener>  createFlattener() throw(std::exception&) WARN_IF_RETURN_UNUSED = 0;
    };
  };
};
#undef PUBLIC_MoFS_PRE
#undef PUBLIC_MoFS_POST
#endif // guard
