libcellml_java_bridge_la_SOURCES += \
  $(top_builddir)/interfaces/p2jSProS.cpp \
  $(top_builddir)/interfaces/j2pSProS.cpp \
  $(top_srcdir)/SProS/sources/SProSBootstrapJava.cpp

libcellml_java_bridge_la_LIBADD += \
  $(top_builddir)/libspros.la

BUILT_SOURCES += \
  $(top_builddir)/interfaces/p2jSProS.cpp \
  $(top_builddir)/interfaces/j2pSProS.cpp

cellml_jar_java += \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Base.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/BaseSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/BaseIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/SEDMLElement.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/NamedElement.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/NamedElementSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/NamedElementIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/NamedIdentifiedElement.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/NamedIdentifiedElementSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/NamedIdentifiedElementIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Model.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ModelSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ModelIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Simulation.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/SimulationSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/SimulationIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/UniformTimeCourse.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Task.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/TaskSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/TaskIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/DataGenerator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/DataGeneratorSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/DataGeneratorIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Output.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/OutputSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/OutputIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Plot2D.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Plot3D.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Report.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Change.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ChangeSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ChangeIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ComputeChange.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ChangeAttribute.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/AddXML.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ChangeXML.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/RemoveXML.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Variable.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/VariableSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/VariableIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Parameter.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ParameterSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/ParameterIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Curve.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/CurveSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/CurveIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/Surface.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/SurfaceSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/SurfaceIterator.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/DataSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/DataSetSet.java \
  $(top_builddir)/interfaces/pjm2pcm/SProS/DataSetIterator.java \
  $(top_builddir)/interfaces/SProS/Base.java \
  $(top_builddir)/interfaces/SProS/BaseSet.java \
  $(top_builddir)/interfaces/SProS/BaseIterator.java \
  $(top_builddir)/interfaces/SProS/Bootstrap.java \
  $(top_builddir)/interfaces/SProS/SEDMLElement.java \
  $(top_builddir)/interfaces/SProS/NamedElement.java \
  $(top_builddir)/interfaces/SProS/NamedElementSet.java \
  $(top_builddir)/interfaces/SProS/NamedElementIterator.java \
  $(top_builddir)/interfaces/SProS/NamedIdentifiedElement.java \
  $(top_builddir)/interfaces/SProS/NamedIdentifiedElementSet.java \
  $(top_builddir)/interfaces/SProS/NamedIdentifiedElementIterator.java \
  $(top_builddir)/interfaces/SProS/Model.java \
  $(top_builddir)/interfaces/SProS/ModelSet.java \
  $(top_builddir)/interfaces/SProS/ModelIterator.java \
  $(top_builddir)/interfaces/SProS/Simulation.java \
  $(top_builddir)/interfaces/SProS/SimulationSet.java \
  $(top_builddir)/interfaces/SProS/SimulationIterator.java \
  $(top_builddir)/interfaces/SProS/UniformTimeCourse.java \
  $(top_builddir)/interfaces/SProS/Task.java \
  $(top_builddir)/interfaces/SProS/TaskSet.java \
  $(top_builddir)/interfaces/SProS/TaskIterator.java \
  $(top_builddir)/interfaces/SProS/DataGenerator.java \
  $(top_builddir)/interfaces/SProS/DataGeneratorSet.java \
  $(top_builddir)/interfaces/SProS/DataGeneratorIterator.java \
  $(top_builddir)/interfaces/SProS/Output.java \
  $(top_builddir)/interfaces/SProS/OutputSet.java \
  $(top_builddir)/interfaces/SProS/OutputIterator.java \
  $(top_builddir)/interfaces/SProS/Plot2D.java \
  $(top_builddir)/interfaces/SProS/Plot3D.java \
  $(top_builddir)/interfaces/SProS/Report.java \
  $(top_builddir)/interfaces/SProS/Change.java \
  $(top_builddir)/interfaces/SProS/ChangeSet.java \
  $(top_builddir)/interfaces/SProS/ChangeIterator.java \
  $(top_builddir)/interfaces/SProS/ComputeChange.java \
  $(top_builddir)/interfaces/SProS/ChangeAttribute.java \
  $(top_builddir)/interfaces/SProS/AddXML.java \
  $(top_builddir)/interfaces/SProS/ChangeXML.java \
  $(top_builddir)/interfaces/SProS/RemoveXML.java \
  $(top_builddir)/interfaces/SProS/Variable.java \
  $(top_builddir)/interfaces/SProS/VariableSet.java \
  $(top_builddir)/interfaces/SProS/VariableIterator.java \
  $(top_builddir)/interfaces/SProS/Parameter.java \
  $(top_builddir)/interfaces/SProS/ParameterSet.java \
  $(top_builddir)/interfaces/SProS/ParameterIterator.java \
  $(top_builddir)/interfaces/SProS/Curve.java \
  $(top_builddir)/interfaces/SProS/CurveSet.java \
  $(top_builddir)/interfaces/SProS/CurveIterator.java \
  $(top_builddir)/interfaces/SProS/Surface.java \
  $(top_builddir)/interfaces/SProS/SurfaceSet.java \
  $(top_builddir)/interfaces/SProS/SurfaceIterator.java \
  $(top_builddir)/interfaces/SProS/DataSet.java \
  $(top_builddir)/interfaces/SProS/DataSetSet.java \
  $(top_builddir)/interfaces/SProS/DataSetIterator.java

cellml_jar_classes += \
  $(top_builddir)/javacp/pjm2pcm/SProS/Base.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/BaseSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/BaseIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/SEDMLElement.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/NamedElement.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/NamedElementSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/NamedElementIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/NamedIdentifiedElement.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/NamedIdentifiedElementSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/NamedIdentifiedElementIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Model.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ModelSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ModelIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Simulation.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/SimulationSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/SimulationIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/UniformTimeCourse.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Task.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/TaskSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/TaskIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/DataGenerator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/DataGeneratorSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/DataGeneratorIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Output.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/OutputSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/OutputIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Plot2D.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Plot3D.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Report.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Change.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ChangeSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ChangeIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ComputeChange.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ChangeAttribute.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/AddXML.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ChangeXML.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/RemoveXML.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Variable.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/VariableSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/VariableIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Parameter.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ParameterSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/ParameterIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Curve.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/CurveSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/CurveIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/Surface.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/SurfaceSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/SurfaceIterator.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/DataSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/DataSetSet.class \
  $(top_builddir)/javacp/pjm2pcm/SProS/DataSetIterator.class \
  $(top_builddir)/javacp/SProS/Base.class \
  $(top_builddir)/javacp/SProS/BaseSet.class \
  $(top_builddir)/javacp/SProS/BaseIterator.class \
  $(top_builddir)/javacp/SProS/Bootstrap.java \
  $(top_builddir)/javacp/SProS/SEDMLElement.class \
  $(top_builddir)/javacp/SProS/NamedElement.class \
  $(top_builddir)/javacp/SProS/NamedElementSet.class \
  $(top_builddir)/javacp/SProS/NamedElementIterator.class \
  $(top_builddir)/javacp/SProS/NamedIdentifiedElement.class \
  $(top_builddir)/javacp/SProS/NamedIdentifiedElementSet.class \
  $(top_builddir)/javacp/SProS/NamedIdentifiedElementIterator.class \
  $(top_builddir)/javacp/SProS/Model.class \
  $(top_builddir)/javacp/SProS/ModelSet.class \
  $(top_builddir)/javacp/SProS/ModelIterator.class \
  $(top_builddir)/javacp/SProS/Simulation.class \
  $(top_builddir)/javacp/SProS/SimulationSet.class \
  $(top_builddir)/javacp/SProS/SimulationIterator.class \
  $(top_builddir)/javacp/SProS/UniformTimeCourse.class \
  $(top_builddir)/javacp/SProS/Task.class \
  $(top_builddir)/javacp/SProS/TaskSet.class \
  $(top_builddir)/javacp/SProS/TaskIterator.class \
  $(top_builddir)/javacp/SProS/DataGenerator.class \
  $(top_builddir)/javacp/SProS/DataGeneratorSet.class \
  $(top_builddir)/javacp/SProS/DataGeneratorIterator.class \
  $(top_builddir)/javacp/SProS/Output.class \
  $(top_builddir)/javacp/SProS/OutputSet.class \
  $(top_builddir)/javacp/SProS/OutputIterator.class \
  $(top_builddir)/javacp/SProS/Plot2D.class \
  $(top_builddir)/javacp/SProS/Plot3D.class \
  $(top_builddir)/javacp/SProS/Report.class \
  $(top_builddir)/javacp/SProS/Change.class \
  $(top_builddir)/javacp/SProS/ChangeSet.class \
  $(top_builddir)/javacp/SProS/ChangeIterator.class \
  $(top_builddir)/javacp/SProS/ComputeChange.class \
  $(top_builddir)/javacp/SProS/ChangeAttribute.class \
  $(top_builddir)/javacp/SProS/AddXML.class \
  $(top_builddir)/javacp/SProS/ChangeXML.class \
  $(top_builddir)/javacp/SProS/RemoveXML.class \
  $(top_builddir)/javacp/SProS/Variable.class \
  $(top_builddir)/javacp/SProS/VariableSet.class \
  $(top_builddir)/javacp/SProS/VariableIterator.class \
  $(top_builddir)/javacp/SProS/Parameter.class \
  $(top_builddir)/javacp/SProS/ParameterSet.class \
  $(top_builddir)/javacp/SProS/ParameterIterator.class \
  $(top_builddir)/javacp/SProS/Curve.class \
  $(top_builddir)/javacp/SProS/CurveSet.class \
  $(top_builddir)/javacp/SProS/CurveIterator.class \
  $(top_builddir)/javacp/SProS/Surface.class \
  $(top_builddir)/javacp/SProS/SurfaceSet.class \
  $(top_builddir)/javacp/SProS/SurfaceIterator.class \
  $(top_builddir)/javacp/SProS/DataSet.class \
  $(top_builddir)/javacp/SProS/DataSetSet.class \
  $(top_builddir)/javacp/SProS/DataSetIterator.class

pure_java += cellml_bootstrap/SProSBootstrap
