DECLARE_EXTENSION(cevas)
DECLARE_IDL(CeVAS)
DECLARE_IDL_DEPENDENCY(CellML_APISPEC)
DECLARE_EXTENSION_END(cevas)

INCLUDE_DIRECTORIES(CeVAS/sources)

ADD_LIBRARY(cevas
  CeVAS/sources/CeVASImpl.cpp)
INSTALL(TARGETS cevas 
    EXPORT libcellml-config
    DESTINATION lib
    INCLUDES DESTINATION ${LIBCELLML_INCLUDE_DEST})
SET_TARGET_PROPERTIES(cevas PROPERTIES VERSION ${GLOBAL_VERSION} SOVERSION ${CEVAS_SOVERSION})
TARGET_LINK_LIBRARIES(cevas cellml ${CMAKE_DL_LIBS})
target_link_libraries(libcellml INTERFACE cevas)
INSTALL(FILES CeVAS/sources/CeVASBootstrap.hpp DESTINATION ${LIBCELLML_INCLUDE_DEST})

DECLARE_BOOTSTRAP("CeVASBootstrap" "CeVAS" "CeVASBootstrap" "cellml_services" "createCeVASBootstrap" "CreateCeVASBootstrap" "CeVASBootstrap.hpp" "CeVAS/sources" "cevas")

DECLARE_CPPUNIT_FILE(CeVAS)
DECLARE_TEST_LIB(cevas)
